[ERROR] 2012-08-22 00:23:00,143 method:com.joyotime.xr87.job.JobException.<init>(JobException.java:28)
读取日志文件[E:\wwwroot\inchengdu\xr87.job/logs/device/log.txt]出错
java.io.FileNotFoundException: E:\wwwroot\inchengdu\xr87.job\logs\device\log.txt (系统找不到指定的文件。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:106)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
[ERROR] 2012-08-22 00:23:00,713 method:com.joyotime.xr87.job.JobException.<init>(JobException.java:28)
获取数据最后一次统计时间出错
com.joyotime.xr87.job.JobException: 读取日志文件[E:\wwwroot\inchengdu\xr87.job/logs/device/log.txt]出错
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:115)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.io.FileNotFoundException: E:\wwwroot\inchengdu\xr87.job\logs\device\log.txt (系统找不到指定的文件。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:106)
	... 10 more
[ERROR] 2012-08-22 00:23:02,395 method:org.quartz.core.JobRunShell.run(JobRunShell.java:222)
Job DEFAULT.jobDeviceDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	... 3 more
[ERROR] 2012-08-22 00:23:02,396 method:org.quartz.core.ErrorLogger.schedulerError(QuartzScheduler.java:2361)
Job (DEFAULT.jobDeviceDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	... 1 more
Caused by: java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	... 3 more
[ERROR] 2012-08-22 00:26:00,085 method:com.joyotime.xr87.job.JobException.<init>(JobException.java:28)
读取日志文件[E:\wwwroot\inchengdu\xr87.job/logs/device/log.txt]出错
java.io.FileNotFoundException: E:\wwwroot\inchengdu\xr87.job\logs\device\log.txt (系统找不到指定的文件。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:106)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
[ERROR] 2012-08-22 00:26:00,494 method:com.joyotime.xr87.job.JobException.<init>(JobException.java:28)
获取数据最后一次统计时间出错
com.joyotime.xr87.job.JobException: 读取日志文件[E:\wwwroot\inchengdu\xr87.job/logs/device/log.txt]出错
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:115)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.io.FileNotFoundException: E:\wwwroot\inchengdu\xr87.job\logs\device\log.txt (系统找不到指定的文件。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:106)
	... 10 more
[ERROR] 2012-08-22 00:26:03,860 method:org.quartz.core.JobRunShell.run(JobRunShell.java:222)
Job DEFAULT.jobDeviceDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at com.joyotime.xr87.job.device.JobDevice.getArea(JobDevice.java:329)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	... 3 more
[ERROR] 2012-08-22 00:26:03,861 method:org.quartz.core.ErrorLogger.schedulerError(QuartzScheduler.java:2361)
Job (DEFAULT.jobDeviceDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: -1]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	... 1 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at com.joyotime.xr87.job.device.JobDevice.getArea(JobDevice.java:329)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	... 3 more
[ERROR] 2012-08-22 00:27:00,561 method:org.quartz.core.JobRunShell.run(JobRunShell.java:222)
Job DEFAULT.jobDeviceDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at com.joyotime.xr87.job.device.JobDevice.getArea(JobDevice.java:329)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	... 3 more
[ERROR] 2012-08-22 00:27:00,565 method:org.quartz.core.ErrorLogger.schedulerError(QuartzScheduler.java:2361)
Job (DEFAULT.jobDeviceDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: -1]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	... 1 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at com.joyotime.xr87.job.device.JobDevice.getArea(JobDevice.java:329)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	... 3 more
[ERROR] 2012-08-22 00:29:52,967 method:org.quartz.core.JobRunShell.run(JobRunShell.java:222)
Job DEFAULT.jobDeviceDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO StatDevice(connectCount,deviceType,deviceCode,province,lastDate,ipArea,createDate,city,ip) VALUES('1','0','windows nt-119.6.126.109','上海','2011-05-25 10:27:51.0','上海市 铁通','2011-05-25 10:27:51.0','','118.26.202.212')]; SQL state [HY000]; error code [1364]; Field 'channelId' doesn't have a default value; nested exception is java.sql.SQLException: Field 'channelId' doesn't have a default value
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO StatDevice(connectCount,deviceType,deviceCode,province,lastDate,ipArea,createDate,city,ip) VALUES('1','0','windows nt-119.6.126.109','上海','2011-05-25 10:27:51.0','上海市 铁通','2011-05-25 10:27:51.0','','118.26.202.212')]; SQL state [HY000]; error code [1364]; Field 'channelId' doesn't have a default value; nested exception is java.sql.SQLException: Field 'channelId' doesn't have a default value
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:428)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	... 3 more
Caused by: java.sql.SQLException: Field 'channelId' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3558)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3490)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2642)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2571)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:782)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:625)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:421)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:396)
	... 11 more
[ERROR] 2012-08-22 00:29:52,971 method:org.quartz.core.ErrorLogger.schedulerError(QuartzScheduler.java:2361)
Job (DEFAULT.jobDeviceDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO StatDevice(connectCount,deviceType,deviceCode,province,lastDate,ipArea,createDate,city,ip) VALUES('1','0','windows nt-119.6.126.109','上海','2011-05-25 10:27:51.0','上海市 铁通','2011-05-25 10:27:51.0','','118.26.202.212')]; SQL state [HY000]; error code [1364]; Field 'channelId' doesn't have a default value; nested exception is java.sql.SQLException: Field 'channelId' doesn't have a default value]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO StatDevice(connectCount,deviceType,deviceCode,province,lastDate,ipArea,createDate,city,ip) VALUES('1','0','windows nt-119.6.126.109','上海','2011-05-25 10:27:51.0','上海市 铁通','2011-05-25 10:27:51.0','','118.26.202.212')]; SQL state [HY000]; error code [1364]; Field 'channelId' doesn't have a default value; nested exception is java.sql.SQLException: Field 'channelId' doesn't have a default value
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	... 1 more
Caused by: org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO StatDevice(connectCount,deviceType,deviceCode,province,lastDate,ipArea,createDate,city,ip) VALUES('1','0','windows nt-119.6.126.109','上海','2011-05-25 10:27:51.0','上海市 铁通','2011-05-25 10:27:51.0','','118.26.202.212')]; SQL state [HY000]; error code [1364]; Field 'channelId' doesn't have a default value; nested exception is java.sql.SQLException: Field 'channelId' doesn't have a default value
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:428)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	... 3 more
Caused by: java.sql.SQLException: Field 'channelId' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3558)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3490)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2642)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2571)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:782)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:625)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:421)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:396)
	... 11 more
[ERROR] 2012-08-22 00:39:30,075 method:com.joyotime.xr87.job.JobException.<init>(JobException.java:28)
读取日志文件[E:\wwwroot\inchengdu\xr87.job/logs/device/log.txt]出错
java.io.FileNotFoundException: E:\wwwroot\inchengdu\xr87.job\logs\device\log.txt (系统找不到指定的文件。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:106)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
[ERROR] 2012-08-22 00:39:30,420 method:com.joyotime.xr87.job.JobException.<init>(JobException.java:28)
获取数据最后一次统计时间出错
com.joyotime.xr87.job.JobException: 读取日志文件[E:\wwwroot\inchengdu\xr87.job/logs/device/log.txt]出错
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:115)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.io.FileNotFoundException: E:\wwwroot\inchengdu\xr87.job\logs\device\log.txt (系统找不到指定的文件。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:106)
	... 10 more
[ERROR] 2012-08-22 00:40:02,049 method:org.quartz.core.JobRunShell.run(JobRunShell.java:222)
Job DEFAULT.jobDeviceDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO StatDevice(connectCount,channelId,deviceType,deviceCode,lastDate,merchantId,createDate,ip) VALUES('1','154','1','android-972ef5100c330731-354120034320836-460011211041927','2011-06-18 01:12:48.0','154','2011-06-18 01:12:48.0','null')]; SQL state [HY000]; error code [1364]; Field 'province' doesn't have a default value; nested exception is java.sql.SQLException: Field 'province' doesn't have a default value
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO StatDevice(connectCount,channelId,deviceType,deviceCode,lastDate,merchantId,createDate,ip) VALUES('1','154','1','android-972ef5100c330731-354120034320836-460011211041927','2011-06-18 01:12:48.0','154','2011-06-18 01:12:48.0','null')]; SQL state [HY000]; error code [1364]; Field 'province' doesn't have a default value; nested exception is java.sql.SQLException: Field 'province' doesn't have a default value
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:428)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	... 3 more
Caused by: java.sql.SQLException: Field 'province' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3558)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3490)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2642)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2571)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:782)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:625)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:421)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:396)
	... 11 more
[ERROR] 2012-08-22 00:40:02,050 method:org.quartz.core.ErrorLogger.schedulerError(QuartzScheduler.java:2361)
Job (DEFAULT.jobDeviceDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO StatDevice(connectCount,channelId,deviceType,deviceCode,lastDate,merchantId,createDate,ip) VALUES('1','154','1','android-972ef5100c330731-354120034320836-460011211041927','2011-06-18 01:12:48.0','154','2011-06-18 01:12:48.0','null')]; SQL state [HY000]; error code [1364]; Field 'province' doesn't have a default value; nested exception is java.sql.SQLException: Field 'province' doesn't have a default value]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'execute' on target class [class com.joyotime.xr87.job.device.JobDevice] failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO StatDevice(connectCount,channelId,deviceType,deviceCode,lastDate,merchantId,createDate,ip) VALUES('1','154','1','android-972ef5100c330731-354120034320836-460011211041927','2011-06-18 01:12:48.0','154','2011-06-18 01:12:48.0','null')]; SQL state [HY000]; error code [1364]; Field 'province' doesn't have a default value; nested exception is java.sql.SQLException: Field 'province' doesn't have a default value
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:320)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	... 1 more
Caused by: org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO StatDevice(connectCount,channelId,deviceType,deviceCode,lastDate,merchantId,createDate,ip) VALUES('1','154','1','android-972ef5100c330731-354120034320836-460011211041927','2011-06-18 01:12:48.0','154','2011-06-18 01:12:48.0','null')]; SQL state [HY000]; error code [1364]; Field 'province' doesn't have a default value; nested exception is java.sql.SQLException: Field 'province' doesn't have a default value
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:428)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	... 3 more
Caused by: java.sql.SQLException: Field 'province' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3558)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3490)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2642)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2571)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:782)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:625)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:421)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:396)
	... 11 more
[ERROR] 2012-08-22 02:05:00,090 method:com.joyotime.xr87.job.JobException.<init>(JobException.java:28)
读取日志文件[E:\wwwroot\inchengdu\xr87.job/logs/settle/log.txt]出错
java.io.FileNotFoundException: E:\wwwroot\inchengdu\xr87.job\logs\settle\log.txt (系统找不到指定的文件。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:106)
	at com.joyotime.xr87.job.settle.JobSettle.execute(JobSettle.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
[ERROR] 2012-08-22 02:05:00,874 method:com.joyotime.xr87.job.JobException.<init>(JobException.java:28)
获取数据最后一次统计时间出错
com.joyotime.xr87.job.JobException: 读取日志文件[E:\wwwroot\inchengdu\xr87.job/logs/settle/log.txt]出错
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:115)
	at com.joyotime.xr87.job.settle.JobSettle.execute(JobSettle.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.io.FileNotFoundException: E:\wwwroot\inchengdu\xr87.job\logs\settle\log.txt (系统找不到指定的文件。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:106)
	... 10 more
[ERROR] 2012-08-22 02:08:00,005 method:com.joyotime.xr87.job.JobException.<init>(JobException.java:28)
读取日志文件[E:\wwwroot\inchengdu\xr87.job/logs/device/log.txt]出错
java.io.FileNotFoundException: E:\wwwroot\inchengdu\xr87.job\logs\device\log.txt (系统找不到指定的文件。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:106)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
[ERROR] 2012-08-22 02:08:00,014 method:com.joyotime.xr87.job.JobException.<init>(JobException.java:28)
获取数据最后一次统计时间出错
com.joyotime.xr87.job.JobException: 读取日志文件[E:\wwwroot\inchengdu\xr87.job/logs/device/log.txt]出错
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:115)
	at com.joyotime.xr87.job.device.JobDevice.execute(JobDevice.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.io.FileNotFoundException: E:\wwwroot\inchengdu\xr87.job\logs\device\log.txt (系统找不到指定的文件。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.joyotime.xr87.job.AbstractJob.readLog(AbstractJob.java:106)
	... 10 more
